// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pgn_analizer_protos/pgn_analizer.proto

package pgn_analyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pgn_analizer_protos_pgn_analizer_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_pgn_analizer_protos_pgn_analizer_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{7, 0}
}

type AnalysisError_ErrorCode int32

const (
	AnalysisError_UNKNOWN        AnalysisError_ErrorCode = 0
	AnalysisError_INVALID_PGN    AnalysisError_ErrorCode = 1
	AnalysisError_GAME_TOO_SHORT AnalysisError_ErrorCode = 2
	AnalysisError_ENGINE_ERROR   AnalysisError_ErrorCode = 3
	AnalysisError_TIMEOUT        AnalysisError_ErrorCode = 4
	AnalysisError_INVALID_DEPTH  AnalysisError_ErrorCode = 5
)

// Enum value maps for AnalysisError_ErrorCode.
var (
	AnalysisError_ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_PGN",
		2: "GAME_TOO_SHORT",
		3: "ENGINE_ERROR",
		4: "TIMEOUT",
		5: "INVALID_DEPTH",
	}
	AnalysisError_ErrorCode_value = map[string]int32{
		"UNKNOWN":        0,
		"INVALID_PGN":    1,
		"GAME_TOO_SHORT": 2,
		"ENGINE_ERROR":   3,
		"TIMEOUT":        4,
		"INVALID_DEPTH":  5,
	}
)

func (x AnalysisError_ErrorCode) Enum() *AnalysisError_ErrorCode {
	p := new(AnalysisError_ErrorCode)
	*p = x
	return p
}

func (x AnalysisError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pgn_analizer_protos_pgn_analizer_proto_enumTypes[1].Descriptor()
}

func (AnalysisError_ErrorCode) Type() protoreflect.EnumType {
	return &file_pgn_analizer_protos_pgn_analizer_proto_enumTypes[1]
}

func (x AnalysisError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisError_ErrorCode.Descriptor instead.
func (AnalysisError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{8, 0}
}

// Request message for PGN analysis
type AnalyzePGNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pgn           string                 `protobuf:"bytes,1,opt,name=pgn,proto3" json:"pgn,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePGNRequest) Reset() {
	*x = AnalyzePGNRequest{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePGNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePGNRequest) ProtoMessage() {}

func (x *AnalyzePGNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePGNRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePGNRequest) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzePGNRequest) GetPgn() string {
	if x != nil {
		return x.Pgn
	}
	return ""
}

func (x *AnalyzePGNRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Simple response with Elo estimates
type AnalyzePGNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	White         *PlayerEloAnalysis     `protobuf:"bytes,1,opt,name=white,proto3" json:"white,omitempty"`
	Black         *PlayerEloAnalysis     `protobuf:"bytes,2,opt,name=black,proto3" json:"black,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePGNResponse) Reset() {
	*x = AnalyzePGNResponse{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePGNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePGNResponse) ProtoMessage() {}

func (x *AnalyzePGNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePGNResponse.ProtoReflect.Descriptor instead.
func (*AnalyzePGNResponse) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzePGNResponse) GetWhite() *PlayerEloAnalysis {
	if x != nil {
		return x.White
	}
	return nil
}

func (x *AnalyzePGNResponse) GetBlack() *PlayerEloAnalysis {
	if x != nil {
		return x.Black
	}
	return nil
}

// Player Elo analysis by phase
type PlayerEloAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opening       int32                  `protobuf:"varint,1,opt,name=opening,proto3" json:"opening,omitempty"`
	Middlegame    int32                  `protobuf:"varint,2,opt,name=middlegame,proto3" json:"middlegame,omitempty"`
	Endgame       int32                  `protobuf:"varint,3,opt,name=endgame,proto3" json:"endgame,omitempty"`
	Overall       int32                  `protobuf:"varint,4,opt,name=overall,proto3" json:"overall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEloAnalysis) Reset() {
	*x = PlayerEloAnalysis{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEloAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEloAnalysis) ProtoMessage() {}

func (x *PlayerEloAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEloAnalysis.ProtoReflect.Descriptor instead.
func (*PlayerEloAnalysis) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerEloAnalysis) GetOpening() int32 {
	if x != nil {
		return x.Opening
	}
	return 0
}

func (x *PlayerEloAnalysis) GetMiddlegame() int32 {
	if x != nil {
		return x.Middlegame
	}
	return 0
}

func (x *PlayerEloAnalysis) GetEndgame() int32 {
	if x != nil {
		return x.Endgame
	}
	return 0
}

func (x *PlayerEloAnalysis) GetOverall() int32 {
	if x != nil {
		return x.Overall
	}
	return 0
}

// Detailed analysis response (for debugging)
type DetailedAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	White         *PlayerEloAnalysis     `protobuf:"bytes,1,opt,name=white,proto3" json:"white,omitempty"`
	Black         *PlayerEloAnalysis     `protobuf:"bytes,2,opt,name=black,proto3" json:"black,omitempty"`
	WhiteStats    *PhaseStatsByPhase     `protobuf:"bytes,3,opt,name=white_stats,json=whiteStats,proto3" json:"white_stats,omitempty"`
	BlackStats    *PhaseStatsByPhase     `protobuf:"bytes,4,opt,name=black_stats,json=blackStats,proto3" json:"black_stats,omitempty"`
	TotalMoves    int32                  `protobuf:"varint,5,opt,name=total_moves,json=totalMoves,proto3" json:"total_moves,omitempty"`
	AnalysisDepth int32                  `protobuf:"varint,6,opt,name=analysis_depth,json=analysisDepth,proto3" json:"analysis_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedAnalysisResponse) Reset() {
	*x = DetailedAnalysisResponse{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedAnalysisResponse) ProtoMessage() {}

func (x *DetailedAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedAnalysisResponse.ProtoReflect.Descriptor instead.
func (*DetailedAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{3}
}

func (x *DetailedAnalysisResponse) GetWhite() *PlayerEloAnalysis {
	if x != nil {
		return x.White
	}
	return nil
}

func (x *DetailedAnalysisResponse) GetBlack() *PlayerEloAnalysis {
	if x != nil {
		return x.Black
	}
	return nil
}

func (x *DetailedAnalysisResponse) GetWhiteStats() *PhaseStatsByPhase {
	if x != nil {
		return x.WhiteStats
	}
	return nil
}

func (x *DetailedAnalysisResponse) GetBlackStats() *PhaseStatsByPhase {
	if x != nil {
		return x.BlackStats
	}
	return nil
}

func (x *DetailedAnalysisResponse) GetTotalMoves() int32 {
	if x != nil {
		return x.TotalMoves
	}
	return 0
}

func (x *DetailedAnalysisResponse) GetAnalysisDepth() int32 {
	if x != nil {
		return x.AnalysisDepth
	}
	return 0
}

// Phase statistics grouped by game phase
type PhaseStatsByPhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opening       *PhaseStats            `protobuf:"bytes,1,opt,name=opening,proto3" json:"opening,omitempty"`
	Middlegame    *PhaseStats            `protobuf:"bytes,2,opt,name=middlegame,proto3" json:"middlegame,omitempty"`
	Endgame       *PhaseStats            `protobuf:"bytes,3,opt,name=endgame,proto3" json:"endgame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseStatsByPhase) Reset() {
	*x = PhaseStatsByPhase{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseStatsByPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseStatsByPhase) ProtoMessage() {}

func (x *PhaseStatsByPhase) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseStatsByPhase.ProtoReflect.Descriptor instead.
func (*PhaseStatsByPhase) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{4}
}

func (x *PhaseStatsByPhase) GetOpening() *PhaseStats {
	if x != nil {
		return x.Opening
	}
	return nil
}

func (x *PhaseStatsByPhase) GetMiddlegame() *PhaseStats {
	if x != nil {
		return x.Middlegame
	}
	return nil
}

func (x *PhaseStatsByPhase) GetEndgame() *PhaseStats {
	if x != nil {
		return x.Endgame
	}
	return nil
}

// Statistics for a specific phase
type PhaseStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveCount     int32                  `protobuf:"varint,1,opt,name=move_count,json=moveCount,proto3" json:"move_count,omitempty"`
	TotalAcpl     int32                  `protobuf:"varint,2,opt,name=total_acpl,json=totalAcpl,proto3" json:"total_acpl,omitempty"`
	AverageAcpl   float64                `protobuf:"fixed64,3,opt,name=average_acpl,json=averageAcpl,proto3" json:"average_acpl,omitempty"`
	EstimatedElo  int32                  `protobuf:"varint,4,opt,name=estimated_elo,json=estimatedElo,proto3" json:"estimated_elo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseStats) Reset() {
	*x = PhaseStats{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseStats) ProtoMessage() {}

func (x *PhaseStats) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseStats.ProtoReflect.Descriptor instead.
func (*PhaseStats) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{5}
}

func (x *PhaseStats) GetMoveCount() int32 {
	if x != nil {
		return x.MoveCount
	}
	return 0
}

func (x *PhaseStats) GetTotalAcpl() int32 {
	if x != nil {
		return x.TotalAcpl
	}
	return 0
}

func (x *PhaseStats) GetAverageAcpl() float64 {
	if x != nil {
		return x.AverageAcpl
	}
	return 0
}

func (x *PhaseStats) GetEstimatedElo() int32 {
	if x != nil {
		return x.EstimatedElo
	}
	return 0
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Health check response
type HealthCheckResponse struct {
	state          protoimpl.MessageState            `protogen:"open.v1"`
	Status         HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pgn_analyzer.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Message        string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp      int64                             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EnginePoolSize int32                             `protobuf:"varint,4,opt,name=engine_pool_size,json=enginePoolSize,proto3" json:"engine_pool_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetEnginePoolSize() int32 {
	if x != nil {
		return x.EnginePoolSize
	}
	return 0
}

// Error details for analysis failures
type AnalysisError struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Code          AnalysisError_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=pgn_analyzer.AnalysisError_ErrorCode" json:"code,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                  `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisError) Reset() {
	*x = AnalysisError{}
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisError) ProtoMessage() {}

func (x *AnalysisError) ProtoReflect() protoreflect.Message {
	mi := &file_pgn_analizer_protos_pgn_analizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisError.ProtoReflect.Descriptor instead.
func (*AnalysisError) Descriptor() ([]byte, []int) {
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisError) GetCode() AnalysisError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return AnalysisError_UNKNOWN
}

func (x *AnalysisError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalysisError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_pgn_analizer_protos_pgn_analizer_proto protoreflect.FileDescriptor

const file_pgn_analizer_protos_pgn_analizer_proto_rawDesc = "" +
	"\n" +
	"&pgn_analizer_protos/pgn_analizer.proto\x12\fpgn_analyzer\";\n" +
	"\x11AnalyzePGNRequest\x12\x10\n" +
	"\x03pgn\x18\x01 \x01(\tR\x03pgn\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\x82\x01\n" +
	"\x12AnalyzePGNResponse\x125\n" +
	"\x05white\x18\x01 \x01(\v2\x1f.pgn_analyzer.PlayerEloAnalysisR\x05white\x125\n" +
	"\x05black\x18\x02 \x01(\v2\x1f.pgn_analyzer.PlayerEloAnalysisR\x05black\"\x81\x01\n" +
	"\x11PlayerEloAnalysis\x12\x18\n" +
	"\aopening\x18\x01 \x01(\x05R\aopening\x12\x1e\n" +
	"\n" +
	"middlegame\x18\x02 \x01(\x05R\n" +
	"middlegame\x12\x18\n" +
	"\aendgame\x18\x03 \x01(\x05R\aendgame\x12\x18\n" +
	"\aoverall\x18\x04 \x01(\x05R\aoverall\"\xd4\x02\n" +
	"\x18DetailedAnalysisResponse\x125\n" +
	"\x05white\x18\x01 \x01(\v2\x1f.pgn_analyzer.PlayerEloAnalysisR\x05white\x125\n" +
	"\x05black\x18\x02 \x01(\v2\x1f.pgn_analyzer.PlayerEloAnalysisR\x05black\x12@\n" +
	"\vwhite_stats\x18\x03 \x01(\v2\x1f.pgn_analyzer.PhaseStatsByPhaseR\n" +
	"whiteStats\x12@\n" +
	"\vblack_stats\x18\x04 \x01(\v2\x1f.pgn_analyzer.PhaseStatsByPhaseR\n" +
	"blackStats\x12\x1f\n" +
	"\vtotal_moves\x18\x05 \x01(\x05R\n" +
	"totalMoves\x12%\n" +
	"\x0eanalysis_depth\x18\x06 \x01(\x05R\ranalysisDepth\"\xb5\x01\n" +
	"\x11PhaseStatsByPhase\x122\n" +
	"\aopening\x18\x01 \x01(\v2\x18.pgn_analyzer.PhaseStatsR\aopening\x128\n" +
	"\n" +
	"middlegame\x18\x02 \x01(\v2\x18.pgn_analyzer.PhaseStatsR\n" +
	"middlegame\x122\n" +
	"\aendgame\x18\x03 \x01(\v2\x18.pgn_analyzer.PhaseStatsR\aendgame\"\x92\x01\n" +
	"\n" +
	"PhaseStats\x12\x1d\n" +
	"\n" +
	"move_count\x18\x01 \x01(\x05R\tmoveCount\x12\x1d\n" +
	"\n" +
	"total_acpl\x18\x02 \x01(\x05R\ttotalAcpl\x12!\n" +
	"\faverage_acpl\x18\x03 \x01(\x01R\vaverageAcpl\x12#\n" +
	"\restimated_elo\x18\x04 \x01(\x05R\festimatedElo\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x91\x02\n" +
	"\x13HealthCheckResponse\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.pgn_analyzer.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10engine_pool_size\x18\x04 \x01(\x05R\x0eenginePoolSize\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"\xef\x01\n" +
	"\rAnalysisError\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2%.pgn_analyzer.AnalysisError.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"o\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vINVALID_PGN\x10\x01\x12\x12\n" +
	"\x0eGAME_TOO_SHORT\x10\x02\x12\x10\n" +
	"\fENGINE_ERROR\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\x11\n" +
	"\rINVALID_DEPTH\x10\x052\x9a\x02\n" +
	"\x14ChessAnalysisService\x12O\n" +
	"\n" +
	"AnalyzePGN\x12\x1f.pgn_analyzer.AnalyzePGNRequest\x1a .pgn_analyzer.AnalyzePGNResponse\x12]\n" +
	"\x12AnalyzePGNDetailed\x12\x1f.pgn_analyzer.AnalyzePGNRequest\x1a&.pgn_analyzer.DetailedAnalysisResponse\x12R\n" +
	"\vHealthCheck\x12 .pgn_analyzer.HealthCheckRequest\x1a!.pgn_analyzer.HealthCheckResponseB\x18Z\x16genprotos/pgn_analyzerb\x06proto3"

var (
	file_pgn_analizer_protos_pgn_analizer_proto_rawDescOnce sync.Once
	file_pgn_analizer_protos_pgn_analizer_proto_rawDescData []byte
)

func file_pgn_analizer_protos_pgn_analizer_proto_rawDescGZIP() []byte {
	file_pgn_analizer_protos_pgn_analizer_proto_rawDescOnce.Do(func() {
		file_pgn_analizer_protos_pgn_analizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgn_analizer_protos_pgn_analizer_proto_rawDesc), len(file_pgn_analizer_protos_pgn_analizer_proto_rawDesc)))
	})
	return file_pgn_analizer_protos_pgn_analizer_proto_rawDescData
}

var file_pgn_analizer_protos_pgn_analizer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pgn_analizer_protos_pgn_analizer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pgn_analizer_protos_pgn_analizer_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: pgn_analyzer.HealthCheckResponse.ServingStatus
	(AnalysisError_ErrorCode)(0),           // 1: pgn_analyzer.AnalysisError.ErrorCode
	(*AnalyzePGNRequest)(nil),              // 2: pgn_analyzer.AnalyzePGNRequest
	(*AnalyzePGNResponse)(nil),             // 3: pgn_analyzer.AnalyzePGNResponse
	(*PlayerEloAnalysis)(nil),              // 4: pgn_analyzer.PlayerEloAnalysis
	(*DetailedAnalysisResponse)(nil),       // 5: pgn_analyzer.DetailedAnalysisResponse
	(*PhaseStatsByPhase)(nil),              // 6: pgn_analyzer.PhaseStatsByPhase
	(*PhaseStats)(nil),                     // 7: pgn_analyzer.PhaseStats
	(*HealthCheckRequest)(nil),             // 8: pgn_analyzer.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 9: pgn_analyzer.HealthCheckResponse
	(*AnalysisError)(nil),                  // 10: pgn_analyzer.AnalysisError
}
var file_pgn_analizer_protos_pgn_analizer_proto_depIdxs = []int32{
	4,  // 0: pgn_analyzer.AnalyzePGNResponse.white:type_name -> pgn_analyzer.PlayerEloAnalysis
	4,  // 1: pgn_analyzer.AnalyzePGNResponse.black:type_name -> pgn_analyzer.PlayerEloAnalysis
	4,  // 2: pgn_analyzer.DetailedAnalysisResponse.white:type_name -> pgn_analyzer.PlayerEloAnalysis
	4,  // 3: pgn_analyzer.DetailedAnalysisResponse.black:type_name -> pgn_analyzer.PlayerEloAnalysis
	6,  // 4: pgn_analyzer.DetailedAnalysisResponse.white_stats:type_name -> pgn_analyzer.PhaseStatsByPhase
	6,  // 5: pgn_analyzer.DetailedAnalysisResponse.black_stats:type_name -> pgn_analyzer.PhaseStatsByPhase
	7,  // 6: pgn_analyzer.PhaseStatsByPhase.opening:type_name -> pgn_analyzer.PhaseStats
	7,  // 7: pgn_analyzer.PhaseStatsByPhase.middlegame:type_name -> pgn_analyzer.PhaseStats
	7,  // 8: pgn_analyzer.PhaseStatsByPhase.endgame:type_name -> pgn_analyzer.PhaseStats
	0,  // 9: pgn_analyzer.HealthCheckResponse.status:type_name -> pgn_analyzer.HealthCheckResponse.ServingStatus
	1,  // 10: pgn_analyzer.AnalysisError.code:type_name -> pgn_analyzer.AnalysisError.ErrorCode
	2,  // 11: pgn_analyzer.ChessAnalysisService.AnalyzePGN:input_type -> pgn_analyzer.AnalyzePGNRequest
	2,  // 12: pgn_analyzer.ChessAnalysisService.AnalyzePGNDetailed:input_type -> pgn_analyzer.AnalyzePGNRequest
	8,  // 13: pgn_analyzer.ChessAnalysisService.HealthCheck:input_type -> pgn_analyzer.HealthCheckRequest
	3,  // 14: pgn_analyzer.ChessAnalysisService.AnalyzePGN:output_type -> pgn_analyzer.AnalyzePGNResponse
	5,  // 15: pgn_analyzer.ChessAnalysisService.AnalyzePGNDetailed:output_type -> pgn_analyzer.DetailedAnalysisResponse
	9,  // 16: pgn_analyzer.ChessAnalysisService.HealthCheck:output_type -> pgn_analyzer.HealthCheckResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pgn_analizer_protos_pgn_analizer_proto_init() }
func file_pgn_analizer_protos_pgn_analizer_proto_init() {
	if File_pgn_analizer_protos_pgn_analizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgn_analizer_protos_pgn_analizer_proto_rawDesc), len(file_pgn_analizer_protos_pgn_analizer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgn_analizer_protos_pgn_analizer_proto_goTypes,
		DependencyIndexes: file_pgn_analizer_protos_pgn_analizer_proto_depIdxs,
		EnumInfos:         file_pgn_analizer_protos_pgn_analizer_proto_enumTypes,
		MessageInfos:      file_pgn_analizer_protos_pgn_analizer_proto_msgTypes,
	}.Build()
	File_pgn_analizer_protos_pgn_analizer_proto = out.File
	file_pgn_analizer_protos_pgn_analizer_proto_goTypes = nil
	file_pgn_analizer_protos_pgn_analizer_proto_depIdxs = nil
}
